# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Build & Deploy PROD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: build_deploy_prod
    runs-on: ubuntu-latest
    permissions:
          id-token: write
          contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test Release
        run: |
          echo "test Release..."  
           