name: Release Staging
on:
  push:
    branches:
      - 'main'
        
jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.1
        id: release                                
        with:
          release-type: simple