name: Release Staging
on:
  push:
    branches:
      - 'main'
        
jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.1
        id: release                                
        with:
          release-type: go
        
      - name: Trigger Build & Deploy Workflow
        run: |
          echo "Dispatching 'release_created' event..."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type": "release_created"}'