name: Release Staging
on:
  push:
    branches:
      - 'main'
        
jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3.1
        id: release                                
        with:
          release-type: simple
 
      - name: Trigger Test Workflow
        run: |
          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type": "release_created"}'
                      